from django.db import models
from django.utils.translation import gettext_lazy as _


class States(models.TextChoices):
    __ = '  ', _('Empty')
    AL = 'AL', _('Alaska')
    AZ = 'AZ', _('Arizona')
    AR = 'AR', _('Arkansas')
    CA = 'CA', _('California')
    CO = 'CO', _('Colorado')
    CT = 'CT', _('Connecticut')
    DE = 'DE', _('Denver')
    DC = 'DC', _('District of Columbia')
    FL = 'FL', _('Florida')
    GA = 'GA', _('Georgia')
    ID = 'ID', _('Idaho')
    IL = 'IL', _('Illinois')
    IN = 'IN', _('Indiana')
    IA = 'IA', _('Iowa')
    KS = 'KS', _('Kansas')
    KY = 'KY', _('Kentucky')
    LA = 'LA', _('Louisiana')
    ME = 'ME', _('Maine')
    MD = 'MD', _('Maryland')
    MA = 'MA', _('Massachusetts')
    MI = 'MI', _('Michigan')
    MN = 'MN', _('Minnesota')
    MS = 'MS', _('Mississippi')
    MO = 'MO', _('Missouri')
    MT = 'MT', _('Montana')
    NB = 'NB', _('Nebraska')
    NV = 'NV', _('Nevada')
    NH = 'NH', _('New Hampshire')
    NJ = 'NJ', _('New Jersey')
    NM = 'NM', _('New Mexico')
    NY = 'NY', _('New York')
    NC = 'NC', _('North Carolina')
    ND = 'ND', _('North Dakota')
    OH = 'OH', _('Ohio')
    OK = 'OK', _('Oklahoma')
    OR = 'OR', _('Oregon')
    PA = 'PA', _('Pennsylvania')
    PR = 'PR', _('Puerto Rico')
    RI = 'RI', _('Rhode Island')
    SC = 'SC', _('South Carolina')
    SD = 'SD', _('South Dakota')
    TN = 'TN', _('Tennessee')
    TX = 'TX', _('Texas')
    UT = 'UT', _('Utah')
    VT = 'VT', _('Vermont')
    VA = 'VA', _('Virginia')
    WA = 'WA', _('Washington')
    WV = 'WV', _('West Virginia')
    WI = 'WI', _('Wisconsin')
    WY = 'WY', _('Wyoming')
