# Generated by Django 3.2.4 on 2021-06-21 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testM',
            fields=[
                ('testID', models.IntegerField(primary_key=True, serialize=False)),
                ('storeName', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('itemID', models.CharField(max_length=30)),
                ('variance', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='testForeignKeyM',
            fields=[
                ('ID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MySQLClient.testm')),
            ],
        ),
    ]
